// source: src/protos/cargo.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.api.Cargo', null, global);
goog.exportSymbol('proto.api.CargoRequest', null, global);
goog.exportSymbol('proto.api.CargoResponse', null, global);
goog.exportSymbol('proto.api.FindCargoRequest', null, global);
goog.exportSymbol('proto.api.FindCargoResponse', null, global);
goog.exportSymbol('proto.api.FindCargoResult', null, global);
goog.exportSymbol('proto.api.FindCargoResult.Owner', null, global);
goog.exportSymbol('proto.api.FindCargoResult.ShortGeo', null, global);
goog.exportSymbol('proto.api.Geo', null, global);
goog.exportSymbol('proto.api.Geo.geo_type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.Cargo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.Cargo.repeatedFields_, null);
};
goog.inherits(proto.api.Cargo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.Cargo.displayName = 'proto.api.Cargo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.CargoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.CargoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.CargoRequest.displayName = 'proto.api.CargoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.CargoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.CargoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.CargoResponse.displayName = 'proto.api.CargoResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.Geo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.Geo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.Geo.displayName = 'proto.api.Geo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindCargoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.FindCargoRequest.repeatedFields_, null);
};
goog.inherits(proto.api.FindCargoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindCargoRequest.displayName = 'proto.api.FindCargoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindCargoResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.FindCargoResult.repeatedFields_, null);
};
goog.inherits(proto.api.FindCargoResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindCargoResult.displayName = 'proto.api.FindCargoResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindCargoResult.ShortGeo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.FindCargoResult.ShortGeo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindCargoResult.ShortGeo.displayName = 'proto.api.FindCargoResult.ShortGeo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindCargoResult.Owner = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.FindCargoResult.Owner, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindCargoResult.Owner.displayName = 'proto.api.FindCargoResult.Owner';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindCargoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.FindCargoResponse.repeatedFields_, null);
};
goog.inherits(proto.api.FindCargoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindCargoResponse.displayName = 'proto.api.FindCargoResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.Cargo.repeatedFields_ = [4,5,11,12,13,14,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.Cargo.prototype.toObject = function(opt_includeInstance) {
  return proto.api.Cargo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.Cargo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Cargo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    loadingpointsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    unloadingpointsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    from: (f = msg.getFrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    till: (f = msg.getTill()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    weight: jspb.Message.getFieldWithDefault(msg, 8, 0),
    volume: jspb.Message.getFieldWithDefault(msg, 9, 0),
    cost: jspb.Message.getFieldWithDefault(msg, 10, 0),
    transporttypeList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    loadingtypeList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    additionList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    additionalphonesList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    additionalmailsList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    currency: jspb.Message.getFieldWithDefault(msg, 16, ""),
    cargotype: jspb.Message.getFieldWithDefault(msg, 17, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.Cargo}
 */
proto.api.Cargo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.Cargo;
  return proto.api.Cargo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.Cargo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.Cargo}
 */
proto.api.Cargo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setLoadingpointsList(value);
      break;
    case 5:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setUnloadingpointsList(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFrom(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTill(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeight(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolume(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCost(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addTransporttype(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addLoadingtype(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddition(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalphones(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalmails(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCargotype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.Cargo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.Cargo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.Cargo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Cargo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLoadingpointsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      4,
      f
    );
  }
  f = message.getUnloadingpointsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      5,
      f
    );
  }
  f = message.getFrom();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTill();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getVolume();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getCost();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getTransporttypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getLoadingtypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getAdditionList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getAdditionalphonesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getAdditionalmailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getCargotype();
  if (f !== 0) {
    writer.writeUint64(
      17,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.Cargo.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.Cargo.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Cargo.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Cargo.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Cargo.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Cargo.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Cargo.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Cargo.prototype.setUpdatedAt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Cargo.prototype.clearUpdatedAt = function() {
  this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Cargo.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated uint64 loadingPoints = 4;
 * @return {!Array<number>}
 */
proto.api.Cargo.prototype.getLoadingpointsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<number>} value */
proto.api.Cargo.prototype.setLoadingpointsList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.api.Cargo.prototype.addLoadingpoints = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Cargo.prototype.clearLoadingpointsList = function() {
  this.setLoadingpointsList([]);
};


/**
 * repeated uint64 unloadingPoints = 5;
 * @return {!Array<number>}
 */
proto.api.Cargo.prototype.getUnloadingpointsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<number>} value */
proto.api.Cargo.prototype.setUnloadingpointsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.api.Cargo.prototype.addUnloadingpoints = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Cargo.prototype.clearUnloadingpointsList = function() {
  this.setUnloadingpointsList([]);
};


/**
 * optional google.protobuf.Timestamp from = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Cargo.prototype.getFrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Cargo.prototype.setFrom = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Cargo.prototype.clearFrom = function() {
  this.setFrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Cargo.prototype.hasFrom = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp till = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Cargo.prototype.getTill = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Cargo.prototype.setTill = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Cargo.prototype.clearTill = function() {
  this.setTill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Cargo.prototype.hasTill = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint32 weight = 8;
 * @return {number}
 */
proto.api.Cargo.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.api.Cargo.prototype.setWeight = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 volume = 9;
 * @return {number}
 */
proto.api.Cargo.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.api.Cargo.prototype.setVolume = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 cost = 10;
 * @return {number}
 */
proto.api.Cargo.prototype.getCost = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.api.Cargo.prototype.setCost = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated string transportType = 11;
 * @return {!Array<string>}
 */
proto.api.Cargo.prototype.getTransporttypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<string>} value */
proto.api.Cargo.prototype.setTransporttypeList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Cargo.prototype.addTransporttype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Cargo.prototype.clearTransporttypeList = function() {
  this.setTransporttypeList([]);
};


/**
 * repeated string loadingType = 12;
 * @return {!Array<string>}
 */
proto.api.Cargo.prototype.getLoadingtypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/** @param {!Array<string>} value */
proto.api.Cargo.prototype.setLoadingtypeList = function(value) {
  jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Cargo.prototype.addLoadingtype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Cargo.prototype.clearLoadingtypeList = function() {
  this.setLoadingtypeList([]);
};


/**
 * repeated string addition = 13;
 * @return {!Array<string>}
 */
proto.api.Cargo.prototype.getAdditionList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/** @param {!Array<string>} value */
proto.api.Cargo.prototype.setAdditionList = function(value) {
  jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Cargo.prototype.addAddition = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Cargo.prototype.clearAdditionList = function() {
  this.setAdditionList([]);
};


/**
 * repeated string additionalPhones = 14;
 * @return {!Array<string>}
 */
proto.api.Cargo.prototype.getAdditionalphonesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/** @param {!Array<string>} value */
proto.api.Cargo.prototype.setAdditionalphonesList = function(value) {
  jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Cargo.prototype.addAdditionalphones = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Cargo.prototype.clearAdditionalphonesList = function() {
  this.setAdditionalphonesList([]);
};


/**
 * repeated string additionalMails = 15;
 * @return {!Array<string>}
 */
proto.api.Cargo.prototype.getAdditionalmailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/** @param {!Array<string>} value */
proto.api.Cargo.prototype.setAdditionalmailsList = function(value) {
  jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Cargo.prototype.addAdditionalmails = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Cargo.prototype.clearAdditionalmailsList = function() {
  this.setAdditionalmailsList([]);
};


/**
 * optional string currency = 16;
 * @return {string}
 */
proto.api.Cargo.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.api.Cargo.prototype.setCurrency = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional uint64 cargoType = 17;
 * @return {number}
 */
proto.api.Cargo.prototype.getCargotype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/** @param {number} value */
proto.api.Cargo.prototype.setCargotype = function(value) {
  jspb.Message.setProto3IntField(this, 17, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.CargoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.CargoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.CargoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.CargoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.CargoRequest}
 */
proto.api.CargoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.CargoRequest;
  return proto.api.CargoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.CargoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.CargoRequest}
 */
proto.api.CargoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.CargoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.CargoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.CargoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.CargoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.CargoRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.CargoRequest.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.CargoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.CargoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.CargoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.CargoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.CargoResponse}
 */
proto.api.CargoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.CargoResponse;
  return proto.api.CargoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.CargoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.CargoResponse}
 */
proto.api.CargoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.CargoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.CargoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.CargoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.CargoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.CargoResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.CargoResponse.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool success = 2;
 * @return {boolean}
 */
proto.api.CargoResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.api.CargoResponse.prototype.setSuccess = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.Geo.prototype.toObject = function(opt_includeInstance) {
  return proto.api.Geo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.Geo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Geo.toObject = function(includeInstance, msg) {
  var f, obj = {
    geoId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.Geo}
 */
proto.api.Geo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.Geo;
  return proto.api.Geo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.Geo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.Geo}
 */
proto.api.Geo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setGeoId(value);
      break;
    case 2:
      var value = /** @type {!proto.api.Geo.geo_type} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.Geo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.Geo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.Geo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Geo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGeoId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.api.Geo.geo_type = {
  CITY: 0,
  REGION: 1,
  COUNTRY: 2
};

/**
 * optional uint64 geo_id = 1;
 * @return {number}
 */
proto.api.Geo.prototype.getGeoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.Geo.prototype.setGeoId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional geo_type type = 2;
 * @return {!proto.api.Geo.geo_type}
 */
proto.api.Geo.prototype.getType = function() {
  return /** @type {!proto.api.Geo.geo_type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.api.Geo.geo_type} value */
proto.api.Geo.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.FindCargoRequest.repeatedFields_ = [1,2,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindCargoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindCargoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindCargoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    geoFromList: jspb.Message.toObjectList(msg.getGeoFromList(),
    proto.api.Geo.toObject, includeInstance),
    geoToList: jspb.Message.toObjectList(msg.getGeoToList(),
    proto.api.Geo.toObject, includeInstance),
    weightFrom: jspb.Message.getFieldWithDefault(msg, 3, 0),
    weightTo: jspb.Message.getFieldWithDefault(msg, 4, 0),
    volumeFrom: jspb.Message.getFieldWithDefault(msg, 5, 0),
    volumeTo: jspb.Message.getFieldWithDefault(msg, 6, 0),
    from: (f = msg.getFrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    till: (f = msg.getTill()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    limit: jspb.Message.getFieldWithDefault(msg, 9, 0),
    offset: jspb.Message.getFieldWithDefault(msg, 10, 0),
    typeloadingList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    timeFilter: (f = msg.getTimeFilter()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cargotype: jspb.Message.getFieldWithDefault(msg, 13, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindCargoRequest}
 */
proto.api.FindCargoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindCargoRequest;
  return proto.api.FindCargoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindCargoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindCargoRequest}
 */
proto.api.FindCargoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.Geo;
      reader.readMessage(value,proto.api.Geo.deserializeBinaryFromReader);
      msg.addGeoFrom(value);
      break;
    case 2:
      var value = new proto.api.Geo;
      reader.readMessage(value,proto.api.Geo.deserializeBinaryFromReader);
      msg.addGeoTo(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeightFrom(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeightTo(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolumeFrom(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolumeTo(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFrom(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTill(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLimit(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffset(value);
      break;
    case 11:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setTypeloadingList(value);
      break;
    case 12:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeFilter(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCargotype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindCargoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindCargoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindCargoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGeoFromList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.api.Geo.serializeBinaryToWriter
    );
  }
  f = message.getGeoToList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.api.Geo.serializeBinaryToWriter
    );
  }
  f = message.getWeightFrom();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getWeightTo();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getVolumeFrom();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getVolumeTo();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getFrom();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTill();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getOffset();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getTypeloadingList();
  if (f.length > 0) {
    writer.writePackedUint32(
      11,
      f
    );
  }
  f = message.getTimeFilter();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCargotype();
  if (f !== 0) {
    writer.writeUint64(
      13,
      f
    );
  }
};


/**
 * repeated Geo geo_from = 1;
 * @return {!Array<!proto.api.Geo>}
 */
proto.api.FindCargoRequest.prototype.getGeoFromList = function() {
  return /** @type{!Array<!proto.api.Geo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.Geo, 1));
};


/** @param {!Array<!proto.api.Geo>} value */
proto.api.FindCargoRequest.prototype.setGeoFromList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.Geo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.Geo}
 */
proto.api.FindCargoRequest.prototype.addGeoFrom = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.Geo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoRequest.prototype.clearGeoFromList = function() {
  this.setGeoFromList([]);
};


/**
 * repeated Geo geo_to = 2;
 * @return {!Array<!proto.api.Geo>}
 */
proto.api.FindCargoRequest.prototype.getGeoToList = function() {
  return /** @type{!Array<!proto.api.Geo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.Geo, 2));
};


/** @param {!Array<!proto.api.Geo>} value */
proto.api.FindCargoRequest.prototype.setGeoToList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.api.Geo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.Geo}
 */
proto.api.FindCargoRequest.prototype.addGeoTo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.api.Geo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoRequest.prototype.clearGeoToList = function() {
  this.setGeoToList([]);
};


/**
 * optional uint32 weight_from = 3;
 * @return {number}
 */
proto.api.FindCargoRequest.prototype.getWeightFrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.api.FindCargoRequest.prototype.setWeightFrom = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 weight_to = 4;
 * @return {number}
 */
proto.api.FindCargoRequest.prototype.getWeightTo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.api.FindCargoRequest.prototype.setWeightTo = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 volume_from = 5;
 * @return {number}
 */
proto.api.FindCargoRequest.prototype.getVolumeFrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.api.FindCargoRequest.prototype.setVolumeFrom = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 volume_to = 6;
 * @return {number}
 */
proto.api.FindCargoRequest.prototype.getVolumeTo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.api.FindCargoRequest.prototype.setVolumeTo = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp from = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.FindCargoRequest.prototype.getFrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.FindCargoRequest.prototype.setFrom = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindCargoRequest.prototype.clearFrom = function() {
  this.setFrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindCargoRequest.prototype.hasFrom = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp till = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.FindCargoRequest.prototype.getTill = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.FindCargoRequest.prototype.setTill = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindCargoRequest.prototype.clearTill = function() {
  this.setTill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindCargoRequest.prototype.hasTill = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional uint32 limit = 9;
 * @return {number}
 */
proto.api.FindCargoRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.api.FindCargoRequest.prototype.setLimit = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 offset = 10;
 * @return {number}
 */
proto.api.FindCargoRequest.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.api.FindCargoRequest.prototype.setOffset = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated uint32 typeLoading = 11;
 * @return {!Array<number>}
 */
proto.api.FindCargoRequest.prototype.getTypeloadingList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<number>} value */
proto.api.FindCargoRequest.prototype.setTypeloadingList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.api.FindCargoRequest.prototype.addTypeloading = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoRequest.prototype.clearTypeloadingList = function() {
  this.setTypeloadingList([]);
};


/**
 * optional google.protobuf.Timestamp time_filter = 12;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.FindCargoRequest.prototype.getTimeFilter = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 12));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.FindCargoRequest.prototype.setTimeFilter = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindCargoRequest.prototype.clearTimeFilter = function() {
  this.setTimeFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindCargoRequest.prototype.hasTimeFilter = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional uint64 cargoType = 13;
 * @return {number}
 */
proto.api.FindCargoRequest.prototype.getCargotype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.api.FindCargoRequest.prototype.setCargotype = function(value) {
  jspb.Message.setProto3IntField(this, 13, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.FindCargoResult.repeatedFields_ = [4,5,11,12,13,14,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindCargoResult.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindCargoResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindCargoResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 2, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 3, ""),
    loadingpointsList: jspb.Message.toObjectList(msg.getLoadingpointsList(),
    proto.api.FindCargoResult.ShortGeo.toObject, includeInstance),
    unloadingpointsList: jspb.Message.toObjectList(msg.getUnloadingpointsList(),
    proto.api.FindCargoResult.ShortGeo.toObject, includeInstance),
    from: jspb.Message.getFieldWithDefault(msg, 6, ""),
    till: jspb.Message.getFieldWithDefault(msg, 7, ""),
    weight: jspb.Message.getFieldWithDefault(msg, 8, 0),
    volume: jspb.Message.getFieldWithDefault(msg, 9, 0),
    cost: jspb.Message.getFieldWithDefault(msg, 10, 0),
    transporttypeList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    loadingtypeList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    additionList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    additionalphonesList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    additionalmailsList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    currency: jspb.Message.getFieldWithDefault(msg, 16, ""),
    owner: (f = msg.getOwner()) && proto.api.FindCargoResult.Owner.toObject(includeInstance, f),
    cargotype: jspb.Message.getFieldWithDefault(msg, 18, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindCargoResult}
 */
proto.api.FindCargoResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindCargoResult;
  return proto.api.FindCargoResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindCargoResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindCargoResult}
 */
proto.api.FindCargoResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new proto.api.FindCargoResult.ShortGeo;
      reader.readMessage(value,proto.api.FindCargoResult.ShortGeo.deserializeBinaryFromReader);
      msg.addLoadingpoints(value);
      break;
    case 5:
      var value = new proto.api.FindCargoResult.ShortGeo;
      reader.readMessage(value,proto.api.FindCargoResult.ShortGeo.deserializeBinaryFromReader);
      msg.addUnloadingpoints(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTill(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeight(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolume(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCost(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addTransporttype(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addLoadingtype(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddition(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalphones(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalmails(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    case 17:
      var value = new proto.api.FindCargoResult.Owner;
      reader.readMessage(value,proto.api.FindCargoResult.Owner.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setCargotype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindCargoResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindCargoResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindCargoResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLoadingpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.api.FindCargoResult.ShortGeo.serializeBinaryToWriter
    );
  }
  f = message.getUnloadingpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.api.FindCargoResult.ShortGeo.serializeBinaryToWriter
    );
  }
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTill();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getVolume();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getCost();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getTransporttypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getLoadingtypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getAdditionList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getAdditionalphonesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getAdditionalmailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.api.FindCargoResult.Owner.serializeBinaryToWriter
    );
  }
  f = message.getCargotype();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindCargoResult.ShortGeo.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindCargoResult.ShortGeo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindCargoResult.ShortGeo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResult.ShortGeo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindCargoResult.ShortGeo}
 */
proto.api.FindCargoResult.ShortGeo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindCargoResult.ShortGeo;
  return proto.api.FindCargoResult.ShortGeo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindCargoResult.ShortGeo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindCargoResult.ShortGeo}
 */
proto.api.FindCargoResult.ShortGeo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindCargoResult.ShortGeo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindCargoResult.ShortGeo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindCargoResult.ShortGeo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResult.ShortGeo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.FindCargoResult.ShortGeo.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.FindCargoResult.ShortGeo.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.api.FindCargoResult.ShortGeo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.ShortGeo.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 type = 3;
 * @return {number}
 */
proto.api.FindCargoResult.ShortGeo.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.api.FindCargoResult.ShortGeo.prototype.setType = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindCargoResult.Owner.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindCargoResult.Owner.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindCargoResult.Owner} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResult.Owner.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindCargoResult.Owner}
 */
proto.api.FindCargoResult.Owner.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindCargoResult.Owner;
  return proto.api.FindCargoResult.Owner.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindCargoResult.Owner} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindCargoResult.Owner}
 */
proto.api.FindCargoResult.Owner.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindCargoResult.Owner.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindCargoResult.Owner.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindCargoResult.Owner} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResult.Owner.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.FindCargoResult.Owner.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.FindCargoResult.Owner.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.api.FindCargoResult.Owner.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.Owner.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.FindCargoResult.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.FindCargoResult.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string created_at = 2;
 * @return {string}
 */
proto.api.FindCargoResult.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.prototype.setCreatedAt = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string updated_at = 3;
 * @return {string}
 */
proto.api.FindCargoResult.prototype.getUpdatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.prototype.setUpdatedAt = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated ShortGeo loadingPoints = 4;
 * @return {!Array<!proto.api.FindCargoResult.ShortGeo>}
 */
proto.api.FindCargoResult.prototype.getLoadingpointsList = function() {
  return /** @type{!Array<!proto.api.FindCargoResult.ShortGeo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.FindCargoResult.ShortGeo, 4));
};


/** @param {!Array<!proto.api.FindCargoResult.ShortGeo>} value */
proto.api.FindCargoResult.prototype.setLoadingpointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.api.FindCargoResult.ShortGeo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.FindCargoResult.ShortGeo}
 */
proto.api.FindCargoResult.prototype.addLoadingpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.api.FindCargoResult.ShortGeo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResult.prototype.clearLoadingpointsList = function() {
  this.setLoadingpointsList([]);
};


/**
 * repeated ShortGeo unloadingPoints = 5;
 * @return {!Array<!proto.api.FindCargoResult.ShortGeo>}
 */
proto.api.FindCargoResult.prototype.getUnloadingpointsList = function() {
  return /** @type{!Array<!proto.api.FindCargoResult.ShortGeo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.FindCargoResult.ShortGeo, 5));
};


/** @param {!Array<!proto.api.FindCargoResult.ShortGeo>} value */
proto.api.FindCargoResult.prototype.setUnloadingpointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.api.FindCargoResult.ShortGeo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.FindCargoResult.ShortGeo}
 */
proto.api.FindCargoResult.prototype.addUnloadingpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.api.FindCargoResult.ShortGeo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResult.prototype.clearUnloadingpointsList = function() {
  this.setUnloadingpointsList([]);
};


/**
 * optional string from = 6;
 * @return {string}
 */
proto.api.FindCargoResult.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.prototype.setFrom = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string till = 7;
 * @return {string}
 */
proto.api.FindCargoResult.prototype.getTill = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.prototype.setTill = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional uint32 weight = 8;
 * @return {number}
 */
proto.api.FindCargoResult.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.api.FindCargoResult.prototype.setWeight = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 volume = 9;
 * @return {number}
 */
proto.api.FindCargoResult.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.api.FindCargoResult.prototype.setVolume = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 cost = 10;
 * @return {number}
 */
proto.api.FindCargoResult.prototype.getCost = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.api.FindCargoResult.prototype.setCost = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated string transportType = 11;
 * @return {!Array<string>}
 */
proto.api.FindCargoResult.prototype.getTransporttypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<string>} value */
proto.api.FindCargoResult.prototype.setTransporttypeList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindCargoResult.prototype.addTransporttype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResult.prototype.clearTransporttypeList = function() {
  this.setTransporttypeList([]);
};


/**
 * repeated string loadingType = 12;
 * @return {!Array<string>}
 */
proto.api.FindCargoResult.prototype.getLoadingtypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/** @param {!Array<string>} value */
proto.api.FindCargoResult.prototype.setLoadingtypeList = function(value) {
  jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindCargoResult.prototype.addLoadingtype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResult.prototype.clearLoadingtypeList = function() {
  this.setLoadingtypeList([]);
};


/**
 * repeated string addition = 13;
 * @return {!Array<string>}
 */
proto.api.FindCargoResult.prototype.getAdditionList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/** @param {!Array<string>} value */
proto.api.FindCargoResult.prototype.setAdditionList = function(value) {
  jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindCargoResult.prototype.addAddition = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResult.prototype.clearAdditionList = function() {
  this.setAdditionList([]);
};


/**
 * repeated string additionalPhones = 14;
 * @return {!Array<string>}
 */
proto.api.FindCargoResult.prototype.getAdditionalphonesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/** @param {!Array<string>} value */
proto.api.FindCargoResult.prototype.setAdditionalphonesList = function(value) {
  jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindCargoResult.prototype.addAdditionalphones = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResult.prototype.clearAdditionalphonesList = function() {
  this.setAdditionalphonesList([]);
};


/**
 * repeated string additionalMails = 15;
 * @return {!Array<string>}
 */
proto.api.FindCargoResult.prototype.getAdditionalmailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/** @param {!Array<string>} value */
proto.api.FindCargoResult.prototype.setAdditionalmailsList = function(value) {
  jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindCargoResult.prototype.addAdditionalmails = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResult.prototype.clearAdditionalmailsList = function() {
  this.setAdditionalmailsList([]);
};


/**
 * optional string currency = 16;
 * @return {string}
 */
proto.api.FindCargoResult.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.prototype.setCurrency = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional Owner owner = 17;
 * @return {?proto.api.FindCargoResult.Owner}
 */
proto.api.FindCargoResult.prototype.getOwner = function() {
  return /** @type{?proto.api.FindCargoResult.Owner} */ (
    jspb.Message.getWrapperField(this, proto.api.FindCargoResult.Owner, 17));
};


/** @param {?proto.api.FindCargoResult.Owner|undefined} value */
proto.api.FindCargoResult.prototype.setOwner = function(value) {
  jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindCargoResult.prototype.clearOwner = function() {
  this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindCargoResult.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional string cargoType = 18;
 * @return {string}
 */
proto.api.FindCargoResult.prototype.getCargotype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/** @param {string} value */
proto.api.FindCargoResult.prototype.setCargotype = function(value) {
  jspb.Message.setProto3StringField(this, 18, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.FindCargoResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindCargoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindCargoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindCargoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    cargosList: jspb.Message.toObjectList(msg.getCargosList(),
    proto.api.FindCargoResult.toObject, includeInstance),
    found: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindCargoResponse}
 */
proto.api.FindCargoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindCargoResponse;
  return proto.api.FindCargoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindCargoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindCargoResponse}
 */
proto.api.FindCargoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.FindCargoResult;
      reader.readMessage(value,proto.api.FindCargoResult.deserializeBinaryFromReader);
      msg.addCargos(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFound(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindCargoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindCargoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindCargoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindCargoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCargosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.api.FindCargoResult.serializeBinaryToWriter
    );
  }
  f = message.getFound();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * repeated FindCargoResult cargos = 1;
 * @return {!Array<!proto.api.FindCargoResult>}
 */
proto.api.FindCargoResponse.prototype.getCargosList = function() {
  return /** @type{!Array<!proto.api.FindCargoResult>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.FindCargoResult, 1));
};


/** @param {!Array<!proto.api.FindCargoResult>} value */
proto.api.FindCargoResponse.prototype.setCargosList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.FindCargoResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.FindCargoResult}
 */
proto.api.FindCargoResponse.prototype.addCargos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.FindCargoResult, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindCargoResponse.prototype.clearCargosList = function() {
  this.setCargosList([]);
};


/**
 * optional uint64 found = 2;
 * @return {number}
 */
proto.api.FindCargoResponse.prototype.getFound = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.api.FindCargoResponse.prototype.setFound = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.api);
