// source: src/protos/truck.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var src_protos_cargo_pb = require('../../src/protos/cargo_pb.js');
goog.object.extend(proto, src_protos_cargo_pb);
goog.exportSymbol('proto.api.FindTruckRequest', null, global);
goog.exportSymbol('proto.api.FindTruckResponse', null, global);
goog.exportSymbol('proto.api.FindTruckResult', null, global);
goog.exportSymbol('proto.api.FindTruckResult.Owner', null, global);
goog.exportSymbol('proto.api.FindTruckResult.ShortGeo', null, global);
goog.exportSymbol('proto.api.Truck', null, global);
goog.exportSymbol('proto.api.TruckRequest', null, global);
goog.exportSymbol('proto.api.TruckResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.Truck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.Truck.repeatedFields_, null);
};
goog.inherits(proto.api.Truck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.Truck.displayName = 'proto.api.Truck';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.TruckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.TruckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.TruckRequest.displayName = 'proto.api.TruckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.TruckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.TruckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.TruckResponse.displayName = 'proto.api.TruckResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindTruckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.FindTruckRequest.repeatedFields_, null);
};
goog.inherits(proto.api.FindTruckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindTruckRequest.displayName = 'proto.api.FindTruckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindTruckResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.FindTruckResult.repeatedFields_, null);
};
goog.inherits(proto.api.FindTruckResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindTruckResult.displayName = 'proto.api.FindTruckResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindTruckResult.ShortGeo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.FindTruckResult.ShortGeo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindTruckResult.ShortGeo.displayName = 'proto.api.FindTruckResult.ShortGeo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindTruckResult.Owner = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.FindTruckResult.Owner, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindTruckResult.Owner.displayName = 'proto.api.FindTruckResult.Owner';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.FindTruckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.FindTruckResponse.repeatedFields_, null);
};
goog.inherits(proto.api.FindTruckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.FindTruckResponse.displayName = 'proto.api.FindTruckResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.Truck.repeatedFields_ = [4,5,11,12,13,14,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.Truck.prototype.toObject = function(opt_includeInstance) {
  return proto.api.Truck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.Truck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Truck.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    loadingpointsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    unloadingpointsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    from: (f = msg.getFrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    till: (f = msg.getTill()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    weight: jspb.Message.getFieldWithDefault(msg, 8, 0),
    volume: jspb.Message.getFieldWithDefault(msg, 9, 0),
    cost: jspb.Message.getFieldWithDefault(msg, 10, 0),
    transporttypeList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    loadingtypeList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    additionList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    additionalphonesList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    additionalmailsList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    currency: jspb.Message.getFieldWithDefault(msg, 16, ""),
    cargotype: jspb.Message.getFieldWithDefault(msg, 17, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.Truck}
 */
proto.api.Truck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.Truck;
  return proto.api.Truck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.Truck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.Truck}
 */
proto.api.Truck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setLoadingpointsList(value);
      break;
    case 5:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setUnloadingpointsList(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFrom(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTill(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeight(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolume(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCost(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addTransporttype(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addLoadingtype(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddition(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalphones(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalmails(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCargotype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.Truck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.Truck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.Truck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.Truck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLoadingpointsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      4,
      f
    );
  }
  f = message.getUnloadingpointsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      5,
      f
    );
  }
  f = message.getFrom();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTill();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getVolume();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getCost();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getTransporttypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getLoadingtypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getAdditionList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getAdditionalphonesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getAdditionalmailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getCargotype();
  if (f !== 0) {
    writer.writeUint64(
      17,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.Truck.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.Truck.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Truck.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Truck.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Truck.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Truck.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Truck.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Truck.prototype.setUpdatedAt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Truck.prototype.clearUpdatedAt = function() {
  this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Truck.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated uint64 loadingPoints = 4;
 * @return {!Array<number>}
 */
proto.api.Truck.prototype.getLoadingpointsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<number>} value */
proto.api.Truck.prototype.setLoadingpointsList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.api.Truck.prototype.addLoadingpoints = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Truck.prototype.clearLoadingpointsList = function() {
  this.setLoadingpointsList([]);
};


/**
 * repeated uint64 unloadingPoints = 5;
 * @return {!Array<number>}
 */
proto.api.Truck.prototype.getUnloadingpointsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<number>} value */
proto.api.Truck.prototype.setUnloadingpointsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.api.Truck.prototype.addUnloadingpoints = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Truck.prototype.clearUnloadingpointsList = function() {
  this.setUnloadingpointsList([]);
};


/**
 * optional google.protobuf.Timestamp from = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Truck.prototype.getFrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Truck.prototype.setFrom = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Truck.prototype.clearFrom = function() {
  this.setFrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Truck.prototype.hasFrom = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp till = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.Truck.prototype.getTill = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.Truck.prototype.setTill = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.Truck.prototype.clearTill = function() {
  this.setTill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.Truck.prototype.hasTill = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint32 weight = 8;
 * @return {number}
 */
proto.api.Truck.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.api.Truck.prototype.setWeight = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 volume = 9;
 * @return {number}
 */
proto.api.Truck.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.api.Truck.prototype.setVolume = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 cost = 10;
 * @return {number}
 */
proto.api.Truck.prototype.getCost = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.api.Truck.prototype.setCost = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated string transportType = 11;
 * @return {!Array<string>}
 */
proto.api.Truck.prototype.getTransporttypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<string>} value */
proto.api.Truck.prototype.setTransporttypeList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Truck.prototype.addTransporttype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Truck.prototype.clearTransporttypeList = function() {
  this.setTransporttypeList([]);
};


/**
 * repeated string loadingType = 12;
 * @return {!Array<string>}
 */
proto.api.Truck.prototype.getLoadingtypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/** @param {!Array<string>} value */
proto.api.Truck.prototype.setLoadingtypeList = function(value) {
  jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Truck.prototype.addLoadingtype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Truck.prototype.clearLoadingtypeList = function() {
  this.setLoadingtypeList([]);
};


/**
 * repeated string addition = 13;
 * @return {!Array<string>}
 */
proto.api.Truck.prototype.getAdditionList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/** @param {!Array<string>} value */
proto.api.Truck.prototype.setAdditionList = function(value) {
  jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Truck.prototype.addAddition = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Truck.prototype.clearAdditionList = function() {
  this.setAdditionList([]);
};


/**
 * repeated string additionalPhones = 14;
 * @return {!Array<string>}
 */
proto.api.Truck.prototype.getAdditionalphonesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/** @param {!Array<string>} value */
proto.api.Truck.prototype.setAdditionalphonesList = function(value) {
  jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Truck.prototype.addAdditionalphones = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Truck.prototype.clearAdditionalphonesList = function() {
  this.setAdditionalphonesList([]);
};


/**
 * repeated string additionalMails = 15;
 * @return {!Array<string>}
 */
proto.api.Truck.prototype.getAdditionalmailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/** @param {!Array<string>} value */
proto.api.Truck.prototype.setAdditionalmailsList = function(value) {
  jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.Truck.prototype.addAdditionalmails = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.Truck.prototype.clearAdditionalmailsList = function() {
  this.setAdditionalmailsList([]);
};


/**
 * optional string currency = 16;
 * @return {string}
 */
proto.api.Truck.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.api.Truck.prototype.setCurrency = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional uint64 cargoType = 17;
 * @return {number}
 */
proto.api.Truck.prototype.getCargotype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/** @param {number} value */
proto.api.Truck.prototype.setCargotype = function(value) {
  jspb.Message.setProto3IntField(this, 17, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.TruckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.TruckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.TruckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.TruckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.TruckRequest}
 */
proto.api.TruckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.TruckRequest;
  return proto.api.TruckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.TruckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.TruckRequest}
 */
proto.api.TruckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.TruckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.TruckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.TruckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.TruckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.TruckRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.TruckRequest.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.TruckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.TruckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.TruckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.TruckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.TruckResponse}
 */
proto.api.TruckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.TruckResponse;
  return proto.api.TruckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.TruckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.TruckResponse}
 */
proto.api.TruckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.TruckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.TruckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.TruckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.TruckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.TruckResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.TruckResponse.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool success = 2;
 * @return {boolean}
 */
proto.api.TruckResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.api.TruckResponse.prototype.setSuccess = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.FindTruckRequest.repeatedFields_ = [1,2,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindTruckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindTruckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindTruckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    geoFromList: jspb.Message.toObjectList(msg.getGeoFromList(),
    src_protos_cargo_pb.Geo.toObject, includeInstance),
    geoToList: jspb.Message.toObjectList(msg.getGeoToList(),
    src_protos_cargo_pb.Geo.toObject, includeInstance),
    weightFrom: jspb.Message.getFieldWithDefault(msg, 3, 0),
    weightTo: jspb.Message.getFieldWithDefault(msg, 4, 0),
    volumeFrom: jspb.Message.getFieldWithDefault(msg, 5, 0),
    volumeTo: jspb.Message.getFieldWithDefault(msg, 6, 0),
    from: (f = msg.getFrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    till: (f = msg.getTill()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    limit: jspb.Message.getFieldWithDefault(msg, 9, 0),
    offset: jspb.Message.getFieldWithDefault(msg, 10, 0),
    typeloadingList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    timeFilter: (f = msg.getTimeFilter()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cargotype: jspb.Message.getFieldWithDefault(msg, 13, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindTruckRequest}
 */
proto.api.FindTruckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindTruckRequest;
  return proto.api.FindTruckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindTruckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindTruckRequest}
 */
proto.api.FindTruckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new src_protos_cargo_pb.Geo;
      reader.readMessage(value,src_protos_cargo_pb.Geo.deserializeBinaryFromReader);
      msg.addGeoFrom(value);
      break;
    case 2:
      var value = new src_protos_cargo_pb.Geo;
      reader.readMessage(value,src_protos_cargo_pb.Geo.deserializeBinaryFromReader);
      msg.addGeoTo(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeightFrom(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeightTo(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolumeFrom(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolumeTo(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFrom(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTill(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLimit(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffset(value);
      break;
    case 11:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setTypeloadingList(value);
      break;
    case 12:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeFilter(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCargotype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindTruckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindTruckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindTruckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGeoFromList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      src_protos_cargo_pb.Geo.serializeBinaryToWriter
    );
  }
  f = message.getGeoToList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      src_protos_cargo_pb.Geo.serializeBinaryToWriter
    );
  }
  f = message.getWeightFrom();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getWeightTo();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getVolumeFrom();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getVolumeTo();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getFrom();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTill();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getOffset();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getTypeloadingList();
  if (f.length > 0) {
    writer.writePackedUint32(
      11,
      f
    );
  }
  f = message.getTimeFilter();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCargotype();
  if (f !== 0) {
    writer.writeUint64(
      13,
      f
    );
  }
};


/**
 * repeated Geo geo_from = 1;
 * @return {!Array<!proto.api.Geo>}
 */
proto.api.FindTruckRequest.prototype.getGeoFromList = function() {
  return /** @type{!Array<!proto.api.Geo>} */ (
    jspb.Message.getRepeatedWrapperField(this, src_protos_cargo_pb.Geo, 1));
};


/** @param {!Array<!proto.api.Geo>} value */
proto.api.FindTruckRequest.prototype.setGeoFromList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.Geo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.Geo}
 */
proto.api.FindTruckRequest.prototype.addGeoFrom = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.Geo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckRequest.prototype.clearGeoFromList = function() {
  this.setGeoFromList([]);
};


/**
 * repeated Geo geo_to = 2;
 * @return {!Array<!proto.api.Geo>}
 */
proto.api.FindTruckRequest.prototype.getGeoToList = function() {
  return /** @type{!Array<!proto.api.Geo>} */ (
    jspb.Message.getRepeatedWrapperField(this, src_protos_cargo_pb.Geo, 2));
};


/** @param {!Array<!proto.api.Geo>} value */
proto.api.FindTruckRequest.prototype.setGeoToList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.api.Geo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.Geo}
 */
proto.api.FindTruckRequest.prototype.addGeoTo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.api.Geo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckRequest.prototype.clearGeoToList = function() {
  this.setGeoToList([]);
};


/**
 * optional uint32 weight_from = 3;
 * @return {number}
 */
proto.api.FindTruckRequest.prototype.getWeightFrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.api.FindTruckRequest.prototype.setWeightFrom = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 weight_to = 4;
 * @return {number}
 */
proto.api.FindTruckRequest.prototype.getWeightTo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.api.FindTruckRequest.prototype.setWeightTo = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 volume_from = 5;
 * @return {number}
 */
proto.api.FindTruckRequest.prototype.getVolumeFrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.api.FindTruckRequest.prototype.setVolumeFrom = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 volume_to = 6;
 * @return {number}
 */
proto.api.FindTruckRequest.prototype.getVolumeTo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.api.FindTruckRequest.prototype.setVolumeTo = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp from = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.FindTruckRequest.prototype.getFrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.FindTruckRequest.prototype.setFrom = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindTruckRequest.prototype.clearFrom = function() {
  this.setFrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindTruckRequest.prototype.hasFrom = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp till = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.FindTruckRequest.prototype.getTill = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.FindTruckRequest.prototype.setTill = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindTruckRequest.prototype.clearTill = function() {
  this.setTill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindTruckRequest.prototype.hasTill = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional uint32 limit = 9;
 * @return {number}
 */
proto.api.FindTruckRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.api.FindTruckRequest.prototype.setLimit = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 offset = 10;
 * @return {number}
 */
proto.api.FindTruckRequest.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.api.FindTruckRequest.prototype.setOffset = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated uint32 typeLoading = 11;
 * @return {!Array<number>}
 */
proto.api.FindTruckRequest.prototype.getTypeloadingList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<number>} value */
proto.api.FindTruckRequest.prototype.setTypeloadingList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.api.FindTruckRequest.prototype.addTypeloading = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckRequest.prototype.clearTypeloadingList = function() {
  this.setTypeloadingList([]);
};


/**
 * optional google.protobuf.Timestamp time_filter = 12;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.api.FindTruckRequest.prototype.getTimeFilter = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 12));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.api.FindTruckRequest.prototype.setTimeFilter = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindTruckRequest.prototype.clearTimeFilter = function() {
  this.setTimeFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindTruckRequest.prototype.hasTimeFilter = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional uint64 cargoType = 13;
 * @return {number}
 */
proto.api.FindTruckRequest.prototype.getCargotype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.api.FindTruckRequest.prototype.setCargotype = function(value) {
  jspb.Message.setProto3IntField(this, 13, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.FindTruckResult.repeatedFields_ = [4,5,11,12,13,14,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindTruckResult.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindTruckResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindTruckResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 2, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 3, ""),
    loadingpointsList: jspb.Message.toObjectList(msg.getLoadingpointsList(),
    proto.api.FindTruckResult.ShortGeo.toObject, includeInstance),
    unloadingpointsList: jspb.Message.toObjectList(msg.getUnloadingpointsList(),
    proto.api.FindTruckResult.ShortGeo.toObject, includeInstance),
    from: jspb.Message.getFieldWithDefault(msg, 6, ""),
    till: jspb.Message.getFieldWithDefault(msg, 7, ""),
    weight: jspb.Message.getFieldWithDefault(msg, 8, 0),
    volume: jspb.Message.getFieldWithDefault(msg, 9, 0),
    cost: jspb.Message.getFieldWithDefault(msg, 10, 0),
    transporttypeList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    loadingtypeList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    additionList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    additionalphonesList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    additionalmailsList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    currency: jspb.Message.getFieldWithDefault(msg, 16, ""),
    owner: (f = msg.getOwner()) && proto.api.FindTruckResult.Owner.toObject(includeInstance, f),
    cargotype: jspb.Message.getFieldWithDefault(msg, 17, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindTruckResult}
 */
proto.api.FindTruckResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindTruckResult;
  return proto.api.FindTruckResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindTruckResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindTruckResult}
 */
proto.api.FindTruckResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new proto.api.FindTruckResult.ShortGeo;
      reader.readMessage(value,proto.api.FindTruckResult.ShortGeo.deserializeBinaryFromReader);
      msg.addLoadingpoints(value);
      break;
    case 5:
      var value = new proto.api.FindTruckResult.ShortGeo;
      reader.readMessage(value,proto.api.FindTruckResult.ShortGeo.deserializeBinaryFromReader);
      msg.addUnloadingpoints(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTill(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeight(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVolume(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCost(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addTransporttype(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addLoadingtype(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddition(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalphones(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdditionalmails(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    case 171:
      var value = new proto.api.FindTruckResult.Owner;
      reader.readMessage(value,proto.api.FindTruckResult.Owner.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setCargotype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindTruckResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindTruckResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindTruckResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLoadingpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.api.FindTruckResult.ShortGeo.serializeBinaryToWriter
    );
  }
  f = message.getUnloadingpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.api.FindTruckResult.ShortGeo.serializeBinaryToWriter
    );
  }
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTill();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getVolume();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getCost();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getTransporttypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getLoadingtypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getAdditionList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getAdditionalphonesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getAdditionalmailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      171,
      f,
      proto.api.FindTruckResult.Owner.serializeBinaryToWriter
    );
  }
  f = message.getCargotype();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindTruckResult.ShortGeo.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindTruckResult.ShortGeo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindTruckResult.ShortGeo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResult.ShortGeo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindTruckResult.ShortGeo}
 */
proto.api.FindTruckResult.ShortGeo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindTruckResult.ShortGeo;
  return proto.api.FindTruckResult.ShortGeo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindTruckResult.ShortGeo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindTruckResult.ShortGeo}
 */
proto.api.FindTruckResult.ShortGeo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindTruckResult.ShortGeo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindTruckResult.ShortGeo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindTruckResult.ShortGeo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResult.ShortGeo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.FindTruckResult.ShortGeo.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.FindTruckResult.ShortGeo.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.api.FindTruckResult.ShortGeo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.ShortGeo.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 type = 3;
 * @return {number}
 */
proto.api.FindTruckResult.ShortGeo.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.api.FindTruckResult.ShortGeo.prototype.setType = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindTruckResult.Owner.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindTruckResult.Owner.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindTruckResult.Owner} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResult.Owner.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindTruckResult.Owner}
 */
proto.api.FindTruckResult.Owner.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindTruckResult.Owner;
  return proto.api.FindTruckResult.Owner.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindTruckResult.Owner} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindTruckResult.Owner}
 */
proto.api.FindTruckResult.Owner.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindTruckResult.Owner.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindTruckResult.Owner.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindTruckResult.Owner} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResult.Owner.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.FindTruckResult.Owner.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.FindTruckResult.Owner.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.api.FindTruckResult.Owner.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.Owner.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.api.FindTruckResult.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.api.FindTruckResult.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string created_at = 2;
 * @return {string}
 */
proto.api.FindTruckResult.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.prototype.setCreatedAt = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string updated_at = 3;
 * @return {string}
 */
proto.api.FindTruckResult.prototype.getUpdatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.prototype.setUpdatedAt = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated ShortGeo loadingPoints = 4;
 * @return {!Array<!proto.api.FindTruckResult.ShortGeo>}
 */
proto.api.FindTruckResult.prototype.getLoadingpointsList = function() {
  return /** @type{!Array<!proto.api.FindTruckResult.ShortGeo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.FindTruckResult.ShortGeo, 4));
};


/** @param {!Array<!proto.api.FindTruckResult.ShortGeo>} value */
proto.api.FindTruckResult.prototype.setLoadingpointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.api.FindTruckResult.ShortGeo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.FindTruckResult.ShortGeo}
 */
proto.api.FindTruckResult.prototype.addLoadingpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.api.FindTruckResult.ShortGeo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResult.prototype.clearLoadingpointsList = function() {
  this.setLoadingpointsList([]);
};


/**
 * repeated ShortGeo unloadingPoints = 5;
 * @return {!Array<!proto.api.FindTruckResult.ShortGeo>}
 */
proto.api.FindTruckResult.prototype.getUnloadingpointsList = function() {
  return /** @type{!Array<!proto.api.FindTruckResult.ShortGeo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.FindTruckResult.ShortGeo, 5));
};


/** @param {!Array<!proto.api.FindTruckResult.ShortGeo>} value */
proto.api.FindTruckResult.prototype.setUnloadingpointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.api.FindTruckResult.ShortGeo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.FindTruckResult.ShortGeo}
 */
proto.api.FindTruckResult.prototype.addUnloadingpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.api.FindTruckResult.ShortGeo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResult.prototype.clearUnloadingpointsList = function() {
  this.setUnloadingpointsList([]);
};


/**
 * optional string from = 6;
 * @return {string}
 */
proto.api.FindTruckResult.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.prototype.setFrom = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string till = 7;
 * @return {string}
 */
proto.api.FindTruckResult.prototype.getTill = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.prototype.setTill = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional uint32 weight = 8;
 * @return {number}
 */
proto.api.FindTruckResult.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.api.FindTruckResult.prototype.setWeight = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 volume = 9;
 * @return {number}
 */
proto.api.FindTruckResult.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.api.FindTruckResult.prototype.setVolume = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 cost = 10;
 * @return {number}
 */
proto.api.FindTruckResult.prototype.getCost = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.api.FindTruckResult.prototype.setCost = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated string transportType = 11;
 * @return {!Array<string>}
 */
proto.api.FindTruckResult.prototype.getTransporttypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<string>} value */
proto.api.FindTruckResult.prototype.setTransporttypeList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindTruckResult.prototype.addTransporttype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResult.prototype.clearTransporttypeList = function() {
  this.setTransporttypeList([]);
};


/**
 * repeated string loadingType = 12;
 * @return {!Array<string>}
 */
proto.api.FindTruckResult.prototype.getLoadingtypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/** @param {!Array<string>} value */
proto.api.FindTruckResult.prototype.setLoadingtypeList = function(value) {
  jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindTruckResult.prototype.addLoadingtype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResult.prototype.clearLoadingtypeList = function() {
  this.setLoadingtypeList([]);
};


/**
 * repeated string addition = 13;
 * @return {!Array<string>}
 */
proto.api.FindTruckResult.prototype.getAdditionList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/** @param {!Array<string>} value */
proto.api.FindTruckResult.prototype.setAdditionList = function(value) {
  jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindTruckResult.prototype.addAddition = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResult.prototype.clearAdditionList = function() {
  this.setAdditionList([]);
};


/**
 * repeated string additionalPhones = 14;
 * @return {!Array<string>}
 */
proto.api.FindTruckResult.prototype.getAdditionalphonesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/** @param {!Array<string>} value */
proto.api.FindTruckResult.prototype.setAdditionalphonesList = function(value) {
  jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindTruckResult.prototype.addAdditionalphones = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResult.prototype.clearAdditionalphonesList = function() {
  this.setAdditionalphonesList([]);
};


/**
 * repeated string additionalMails = 15;
 * @return {!Array<string>}
 */
proto.api.FindTruckResult.prototype.getAdditionalmailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/** @param {!Array<string>} value */
proto.api.FindTruckResult.prototype.setAdditionalmailsList = function(value) {
  jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.api.FindTruckResult.prototype.addAdditionalmails = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResult.prototype.clearAdditionalmailsList = function() {
  this.setAdditionalmailsList([]);
};


/**
 * optional string currency = 16;
 * @return {string}
 */
proto.api.FindTruckResult.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.prototype.setCurrency = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional Owner owner = 171;
 * @return {?proto.api.FindTruckResult.Owner}
 */
proto.api.FindTruckResult.prototype.getOwner = function() {
  return /** @type{?proto.api.FindTruckResult.Owner} */ (
    jspb.Message.getWrapperField(this, proto.api.FindTruckResult.Owner, 171));
};


/** @param {?proto.api.FindTruckResult.Owner|undefined} value */
proto.api.FindTruckResult.prototype.setOwner = function(value) {
  jspb.Message.setWrapperField(this, 171, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.api.FindTruckResult.prototype.clearOwner = function() {
  this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.FindTruckResult.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 171) != null;
};


/**
 * optional string cargoType = 17;
 * @return {string}
 */
proto.api.FindTruckResult.prototype.getCargotype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.api.FindTruckResult.prototype.setCargotype = function(value) {
  jspb.Message.setProto3StringField(this, 17, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.FindTruckResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.FindTruckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.FindTruckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.FindTruckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    trucksList: jspb.Message.toObjectList(msg.getTrucksList(),
    proto.api.FindTruckResult.toObject, includeInstance),
    found: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.FindTruckResponse}
 */
proto.api.FindTruckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.FindTruckResponse;
  return proto.api.FindTruckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.FindTruckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.FindTruckResponse}
 */
proto.api.FindTruckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.FindTruckResult;
      reader.readMessage(value,proto.api.FindTruckResult.deserializeBinaryFromReader);
      msg.addTrucks(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFound(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.FindTruckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.FindTruckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.FindTruckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.FindTruckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrucksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.api.FindTruckResult.serializeBinaryToWriter
    );
  }
  f = message.getFound();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * repeated FindTruckResult trucks = 1;
 * @return {!Array<!proto.api.FindTruckResult>}
 */
proto.api.FindTruckResponse.prototype.getTrucksList = function() {
  return /** @type{!Array<!proto.api.FindTruckResult>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.FindTruckResult, 1));
};


/** @param {!Array<!proto.api.FindTruckResult>} value */
proto.api.FindTruckResponse.prototype.setTrucksList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.FindTruckResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.FindTruckResult}
 */
proto.api.FindTruckResponse.prototype.addTrucks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.FindTruckResult, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.api.FindTruckResponse.prototype.clearTrucksList = function() {
  this.setTrucksList([]);
};


/**
 * optional uint64 found = 2;
 * @return {number}
 */
proto.api.FindTruckResponse.prototype.getFound = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.api.FindTruckResponse.prototype.setFound = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.api);
